highlighter: rouge
baseurl: /esc17
menu_header: ESC17
exercises_repo: https://github.com/infn-esc/esc17/blob/gh-pages
menu:
  -
    name: basic
    label: BASICS
    items:
    - name: environment
      label: Environment
    - name: compiling
      label: Compiling
    - name: formatting
      label: Formatting
    - name: valgrind
      label: Valgrind
    - name: igprof
      label: IgProf
  - name: architecture
    label: ARCHITECTURE
    items:
    - name: perf
      label: perf
  - name: cpp
    label: C++ and MEMORY
    items:
    - name: algorithms
      label: Algorithms
    - name: issues
      label: Memory issues
    - name: pointers
      label: Smart pointers
    - name: move
      label: Move
    - name: layout
      label: Data layout
    - name: vector_vs_list
      label: vector vs list
    - name: contract
      label: Contracts
    - name: tidy
      label: Static analysis

  -
    name: floatingpoint
    label: FLOATING POINT
    items:
    - name: fpbasic
      label: Basic
    - name: quadsolver
      label: Second Order Equation
  -
    name: vectorization
    label: VECTORIZATION
    items:
    - name: pi
      label: Vectorize computation of pi
    - name: binning
      label: Vectorize the filling of an histogram

defaults:
  -
    scope:
      path: "basic/"
      type: "posts"
    values:
      category: "basic"
      layout: "main"
